select * from tbl_credentials;
select * from tbl_credentials;
--drop table tbl_credentials CASCADE CONSTRAINTS;
insert into tbl_credentials(id,password,type) values('a','a','ADMIN');
select * from tbl_bidder;
insert into tbl_bidder(id,email) values(23489,'abc@gmail.com');
commit;
delete from tbl_bidinfo where sell_request_id=63;
select * from tbl_bidInfo;
select * from tbl_farmer;
select * from tbl_bidder;
select * from tbl_sellrequest;
select * from tbl_credentials;
update tbl_credentials set password='w' where type='BIDDER';
select * from tbl_admin_request;
insert into tbl_admin_request values(999,0,2);
insert into tbl_farmer(id,name) values(888,'yash8');
insert into tbl_bidder(id,name) values(999,'bidder99');
insert into tbl_farmer set name='yash' where id=222;
commit;
select * from tbl_bidinfo;
drop table tbl_bidinfo cascade constraint;
drop table tbl_bidder cascade constraint;